version: "3.8"
services:
  sillybots:
    image: "ghcr.io/juni-b-queer/silly-answer-bot:main"
    depends_on:
      - jetstream
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sessionData:/sessionData
    networks:
      - bun

  usertracker:
    image: "ghcr.io/juni-b-queer/bsky-user-activity-bot:main"
    depends_on:
      - jetstream
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sessionData:/sessionData
    networks:
      - bun

  reminderbot:
    image: "ghcr.io/juni-b-queer/bsky-remind-me-bot:development"
    depends_on:
      - jetstream
      - mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./sessionData:/sessionData
    networks:
      - bun

  jetstream:
    image: "ghcr.io/juni-b-queer/jetstream-new:personal-branch"
    container_name: jetstream
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - CURSOR_FILE=/data/cursor.json
    ports:
      - "6008:6008"
    volumes:
      - ./data:/data
    networks:
      - bun

  mysql:
    image: "mysql:8.0"
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./mysql/db:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
    networks:
      - bun

networks:
  bun:
    driver: bridge
